Support multiple API versions
exasol/extension-manager pull request #102
Opened 2023-06-22 08:01 UTC by kaklakariada

Closes #29

2023-06-26 11:06 UTC, redcatbear requested changes

2023-06-27 05:20 UTC, kaklakariada commented on go.sum
Strange. It already is in `.gitattributes`:

```
go.sum                                              linguist-generated=true
```

2023-06-27 05:27 UTC, kaklakariada commented on pkg/extensionAPI/version_test.go
> +	err := checkCompatibleVersion("id", currentMajorVersion+".99.99")
I use a formatter. There are standard rules for Go. The formatter removes spaces here when I add them manually.

2023-06-27 05:29 UTC, kaklakariada commented on pkg/integrationTesting/testExtensionBuilder.go
>  func (b TestExtensionBuilder) Build() *BuiltExtension {
Using a one-letter name for the "self" pointer is custom in Go. However I will rename it ;)

2023-06-27 05:58 UTC, kaklakariada commented on pkg/integrationTesting/testExtensionBuilder.go
> +	workDir := b.createWorkDir()
In this special case we want to keep the directory to avoid running `npm install` for each test to save time.

2023-06-27 07:01 UTC, redcatbear approved these changes

2023-06-27 07:20 UTC, merged