#26 Add endpoint for creating an instance
exasol/extension-manager pull request #47
Opened 2022-07-28 15:28 UTC by kaklakariada

Closes #26

2022-08-08 12:31 UTC, kaklakariada commented on extensionAPI/extensionApi.go
> +			return &v
Good point. I wanted to explicitly return `nil`, but I guess it would be better to add a return value like "found".

2022-08-08 12:38 UTC, kaklakariada commented on extensionAPI/errorHandlingExtension.go
> +		if err := recover(); err != nil {
Good point. We call JavaScript code here, and JS can only throw Errors/panic when something goes wrong.
This struct just wraps this behavior to use 'standard' Go errors.

2022-08-08 12:39 UTC, kaklakariada commented on extensionController/extensionController.go
> +	}
Good idea, thanks!

2022-08-08 12:47 UTC, kaklakariada commented on parameterValidator/parameterValidator.go
> +	}
Done

2022-08-08 12:47 UTC, kaklakariada commented on parameterValidator/parameterValidator.go
> +	}
Done

2022-08-08 12:48 UTC, kaklakariada commented on parameterValidator/parameterValidator.go
>  	_ "embed"
Yes, for embedding the validator JS code.
Added comment.

2022-08-08 12:50 UTC, kaklakariada commented on restAPI/restApi.go
> +	result, err := restApi.createInstance(c)
Creating an instance of the extension is the goal of the put request.

2022-08-08 12:56 UTC, kaklakariada commented on parameterValidator/parameterValidator.go
> +		id, name, err := extractFromDefinition(def)
Done

2022-08-08 12:56 UTC, kaklakariada commented on extensionAPI/extensionApi.go
> +func (pv ParameterValues) Find(id string) *ParameterValue {
Refactored to return a value

2022-08-08 14:03 UTC, Nicoretti submitted a review, later dismissed

2022-08-09 07:44 UTC, ckunki requested changes

2022-08-09 07:44 UTC, ckunki commented on parameterValidator/parameterValidator_test.go
> +			expected:    []ValidationResult{{Success: false, Message: `Failed to validate parameter "My param": This is a required field.`}}},
Proposal:
* always use the same word e.g. "input" -- not "param" vs. "field"

2022-08-09 09:24 UTC, merged